import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { TrainerProvider } from "@/providers/trainer";
import { UserProvider } from "@/providers/userlogin";
import { ClientProvider } from "@/providers/client";

import { FoodProvider } from "@/providers/food-items";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const fitnessColors = {
  token: {
    colorPrimary: "#07c727",
    colorInfo: "#07c727",
    colorBgBase: "#fafbff",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider theme={fitnessColors}>
      <TrainerProvider>
        <ClientProvider>
          <UserProvider>
            <FoodProvider>
              <html lang="en">
                <body className={`${geistSans.variable} ${geistMono.variable}`}>
                  {children}
                </body>
              </html>
            </FoodProvider>
          </UserProvider>
        </ClientProvider>
      </TrainerProvider>
    </ConfigProvider>
  );
}
